# -*- coding: utf-8 -*-
"""User Input and Error Handling - Solutions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FTxCjyWv0Ns7788vmBxNGTVYPWi9eRcd

# User Input and Error Handling - Solutions

## Problem 1

Write a bill-splitting program that:
1. Asks the user for the total bill amount
2. Asks the user for the number of people splitting the bill
3. Prints how much each person owes, rounded to 2 decimal places

Make sure to cast the inputs to the appropriate numeric types.

**Sample output**
```
Each person owes $15.00.
```
"""

# TODO write your program here

"""### Solution"""

bill = float(input("Enter the total bill amount: "))
people = int(input("Enter the number of people: "))
share = bill / people
print(f"Each person owes ${share:.2f}.")

"""## Problem 2

Update your bill-splitting program to handle the case where the user enters something that isn't a number. Use a `try/except` block to catch this error and print: `"Please enter valid numbers."`

**Sample output**
```
Each person owes $15.00.
```
```
Please enter valid numbers.
```
"""

# TODO write your program here

"""### Solution"""

try:
    bill = float(input("Enter the total bill amount: "))
    people = int(input("Enter the number of people: "))
    share = bill / people
    print(f"Each person owes ${share:.2f}.")
except ValueError:
    print("Please enter valid numbers.")

"""## Problem 3

Update your bill-splitting program one more time to also handle the case where the user enters `0` for the number of people. Use two `except` blocks to handle these two error cases separately:
- If either input is not a number, print: `"Please enter valid numbers."`
- If the number of people is zero, print: `"Error: The number of people cannot be zero."`

**Sample output**
```
Each person owes $15.00.
```
```
Please enter valid numbers.
```
```
Error: The number of people cannot be zero.
```
"""

# TODO write your program here

"""### Solution"""

try:
    bill = float(input("Enter the total bill amount: "))
    people = int(input("Enter the number of people: "))
    share = bill / people
    print(f"Each person owes ${share:.2f}.")
except ValueError:
    print("Please enter valid numbers.")
except ZeroDivisionError:
    print("Error: The number of people cannot be zero.")