# -*- coding: utf-8 -*-
"""Lambda Functions - Practice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11A5BatYggJsWuYZ2YHwZx-9teCFBJhZ4

<img src="https://drive.google.com/uc?id=1uPUwnTqN6FmhirxTGO-nPf-G4lSF3dn5" alt="Banner" width="1500">

# Practice Lambda Functions

### Note

The exercises in this workbook ask you to write lambda functions and assign them to variables. There is pre-written code to call your lambda function assigned to a varaible with parameter(s). This is to allow you to practice the syntax. However in practice, lambda functions are mostly passed into functions, not assigned to variables.

## Exercise 1: Basic Syntax
Write a lambda function that takes a number and returns its square. Assign it to a variable called `square`, and test it on the number `5`.
"""

square = # your code here
print(square(5))

"""## Exercise 2: Multiple Parameters
Write a lambda function that takes two numbers and returns their product. Assign it to a variable `multiply`, and test it on the numbers `3` and `7`.
"""

multiply = # your code here
print(multiply(3, 7))

"""## Exercise 3: Using `map()`
You are given a list of numbers:
```python
nums = [1, 2, 3, 4, 5]
```
Use `map()` with a lambda function to double each number in the list. Convert the result to a list and print it.
"""

nums = [1, 2, 3, 4, 5]
doubled = # your code here
print(list(doubled))

"""## Exercise 4: Using `filter()`
Use `filter()` and a lambda function to select only the words in this list that are longer than 4 characters:
```python
words = ['hi', 'hello', 'sun', 'amazing', 'cat']
```
"""

words = ['hi', 'hello', 'sun', 'amazing', 'cat']
long_words = # your code here
print(list(long_words))

"""## Exercise 5: Sorting with Lambda
You are given a list of tuples, where each tuple contains a name and a score:
```python
students = [('Alice', 88), ('Bob', 72), ('Charlie', 95)]
```
Use the `sorted()` function and a lambda to sort the list **by score in descending order**.
"""

students = [('Alice', 88), ('Bob', 72), ('Charlie', 95)]
sorted_students = # your code here
print(sorted_students)