# -*- coding: utf-8 -*-
"""Dictionaries - Solutions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z2CWlJNOxfXQOjjTjZJVQ8iZPsSYVr7V

<img src="https://drive.google.com/uc?id=1uPUwnTqN6FmhirxTGO-nPf-G4lSF3dn5" alt="Banner" width="1500">

# Dictionaries - Solutions

## Problem 1

Create a dictionary called `capitals` that maps three countries to their capital cities:

- "France" → "Paris"
- "Japan" → "Tokyo"
- "Canada" → "Ottawa"

Then print the capital of Japan using its country name as the key.

**Sample output**
```
Tokyo
```
"""

# TODO create the capitals dictionary

# TODO print Japan's capital

"""### Solution"""

capitals = {
    "France": "Paris",
    "Japan": "Tokyo",
    "Canada": "Ottawa"
}

print(capitals["Japan"])

"""## Problem 2

You're managing the menu for a small café. Starting with the menu below:

- Add a new item: "latte" → 4.50
- Remove "drip coffee" — it's been discontinued

Print the updated menu.
"""

menu = {
    "espresso": 3.00,
    "drip coffee": 2.00,
    "croissant": 3.50,
    "muffin": 2.75
}

# TODO add latte to the menu

# TODO remove drip coffee

"""### Solution"""

menu = {
    "espresso": 3.00,
    "drip coffee": 2.00,
    "croissant": 3.50,
    "muffin": 2.75
}

menu["latte"] = 4.50
menu.pop("drip coffee")

print(menu)

"""## Problem 3

You have a dictionary of students and their test scores.

Use dictionary methods to:

1. Print all student names using `keys()`
2. Use `items()` to print only the students who scored above 80

**Sample output**
```
Students:
Alice
Bob
Carol
Dave
Eve

Students who scored above 80:
Alice: 92
Carol: 85
Eve: 95
```
"""

scores = {
    "Alice": 92,
    "Bob": 78,
    "Carol": 85,
    "Dave": 61,
    "Eve": 95
}

# TODO print all student names using keys()

# TODO print students who scored above 80 using items()

"""### Solution"""

scores = {
    "Alice": 92,
    "Bob": 78,
    "Carol": 85,
    "Dave": 61,
    "Eve": 95
}

print("Students:")
for name in scores.keys():
    print(name)

print("\nStudents who scored above 80:")
for name, score in scores.items():
    if score > 80:
        print(f"{name}: {score}")