# -*- coding: utf-8 -*-
"""Integers vs Floats - Solutions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hEClC1HS96Hlyiguz-RmhH7TWBc--SiK

<img src="https://drive.google.com/uc?id=1uPUwnTqN6FmhirxTGO-nPf-G4lSF3dn5" alt="Banner" width="1500">

# Integers vs Floats - Solutions

## Problem 1

Below are several numbers. For each one, predict whether it's an integer or a float, then use the `type()` function to check your prediction.

Numbers to check:
- `42`
- `3.14`
- `0`
- `0.0`
"""

# TODO: Check the type of each number using type()

"""### Solution"""

print(type(42))
print(type(3.14))
print(type(0))
print(type(0.0))

"""## Problem 2

You have 17 books and want to distribute them evenly among 4 shelves.

Calculate:
1. How many books each shelf gets if you divide them equally (use regular division `/`)
2. How many whole books each shelf gets (use integer division `//`)
3. How many books are left over (use the modulo operator `%`)

**Sample output:**
```
4.25
4
1
```
"""

# TODO: Calculate 17 / 4


# TODO: Calculate 17 // 4


# TODO: Calculate 17 % 4

"""### Solution"""

# Regular division
print(17 / 4)

# Integer division
print(17 // 4)

# Modulo (remainder)
print(17 % 4)

"""## Problem 3

When you mix integers and floats in calculations, Python automatically handles the conversion.

For each expression below, predict whether the result will be an integer or a float. Then print both the result and its type to verify.

Expressions:
1. `5 + 3`
2. `5 + 3.0`
3. `15 // 3`
4. `15.0 // 3`
"""

# TODO: For each expression, print both the result and its type
# Hint: You can print multiple things at once like this: print(5 + 3, type(5 + 3))

"""### Solution"""

print(5 + 3, type(5 + 3))
print(5 + 3.0, type(5 + 3.0))
print(15 // 3, type(15 // 3))
print(15.0 // 3, type(15.0 // 3))