# -*- coding: utf-8 -*-
"""Lists Tuples Sets - Solutions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bsBvMRAHKsdOW_PtEhsluV6CpHdPI_zK

<img src="https://drive.google.com/uc?id=1uPUwnTqN6FmhirxTGO-nPf-G4lSF3dn5" alt="Banner" width="1500">

# Lists, Tuples, and Sets - Solutions

## Problem 1 – Choosing the Right Collection

For each scenario below, decide whether a **list**, **tuple**, or **set** is the best choice. Then create the collection with the given data.

**Scenario A:** Store your birthday (month: 7, day: 4, year: 1995). These values should never change.

**Scenario B:** Store a shopping list that you'll add items to as you think of them.

**Scenario C:** Store the unique genres of movies in your collection (you have: "action", "comedy", "action", "drama", "comedy", "horror").
"""

# Scenario A: Birthday that should never change
# TODO: Create the appropriate collection


# Scenario B: Shopping list you'll add items to
# TODO: Create the appropriate collection


# Scenario C: Unique movie genres
# TODO: Create the appropriate collection

"""### Solution"""

# Scenario A: Birthday that should never change
# Use a TUPLE - data that shouldn't be modified
birthday = (7, 4, 1995)
print(birthday)

# Scenario B: Shopping list you'll add items to
# Use a LIST - ordered and needs to be modified
shopping_list = ["milk", "eggs", "bread"]
shopping_list.append("butter")
print(shopping_list)

# Scenario C: Unique movie genres
# Use a SET - automatically removes duplicates
movie_genres = {"action", "comedy", "action", "drama", "comedy", "horror"}
print(movie_genres)

"""## Problem 2 – Removing Duplicates

You have a list of website visitors, but some visitors appear more than once:

```python
visitors = ["diana", "bob", "charlie", "diana", "bob", "alice", "charlie", "diana"]
```

Write code to get a list of unique visitors (no duplicates), sorted alphabetically. Print the result.
"""

visitors = ["diana", "bob", "charlie", "diana", "bob", "alice", "charlie", "diana"]

# TODO: Get a list of unique visitors, sorted alphabetically

"""### Solution"""

visitors = ["diana", "bob", "charlie", "diana", "bob", "alice", "charlie", "diana"]

unique_visitors = list(set(visitors))
unique_visitors.sort()
print(unique_visitors)

"""## Problem 3 – Modifying Collections

You're managing a team roster and want to compare how modifications work on a list vs. a set. Start with these collections:

```python
team_list = ["alice", "bob", "charlie"]
team_set = {"alice", "bob", "charlie"}
```

Perform the following operations on **both** collections:

1. Add "diana" to the team
2. Remove "bob" from the team
3. Print both collections

Then answer: Why can't you change "charlie" to "chuck" the same way in both collections?
"""

team_list = ["alice", "bob", "charlie"]
team_set = {"alice", "bob", "charlie"}

# TODO: Add "diana" to both collections


# TODO: Remove "bob" from both collections


# TODO: Print both collections

"""### Solution"""

team_list = ["alice", "bob", "charlie"]
team_set = {"alice", "bob", "charlie"}

# Add "diana" to both collections
team_list.append("diana")
team_set.add("diana")

# Remove "bob" from both collections
team_list.remove("bob")
team_set.remove("bob")

# Print both collections
print("List:", team_list)
print("Set:", team_set)

# To change "charlie" to "chuck":
# In a LIST, you can use indexing:
team_list[1] = "chuck"
# In a SET, you can't use indexing because sets are unordered.
# Instead, you must remove "charlie" and add "chuck":
team_set.remove("charlie")
team_set.add("chuck")
print("Set after rename:", team_set)