# -*- coding: utf-8 -*-
"""Booleans and Conditionals - Exercises.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jr2M-v4ZghVMuUAXTnU4aXjkQR20KHNI

<img src="https://drive.google.com/uc?id=1uPUwnTqN6FmhirxTGO-nPf-G4lSF3dn5" alt="Banner" width="1500">


# Booleans and Conditionals - Exercises

## Problem 1
Write a program that checks if a user's age qualifies them for a movie discount. If the age is 12 or under, print "You get a child discount!". Otherwise, print "Regular ticket price applies".

**Sample output**
```
age = 10
You get a child discount!

age = 15
Regular ticket price applies
```
"""

# TODO write the age discount checker
age = 10

"""## Problem 2
Write a program that checks if a password is strong enough. A password is considered strong if it has 8 or more characters. Based on the result of the comparison, print either "Password is strong" or "Password is too weak".

**Sample output**
```
password = "abc123"
Password is too weak

password = "securepass2024"
Password is strong
```
"""

# TODO write the password strength checker
password = "abc123"

"""## Problem 3
Write a program that acts as a smart home thermostat. It should:
- Check if the current temperature is below the desired temperature
- If yes, print "Turning on heater" and then print "Current temperature: [temp]°F"
- If no, print "Temperature is comfortable" and then print "Current temperature: [temp]°F"
- After the if-else block, always print "Thermostat check complete"

**Sample output**
```
current_temp = 65
desired_temp = 72
Turning on heater
Current temperature: 65°F
Thermostat check complete

current_temp = 75
desired_temp = 72
Temperature is comfortable
Current temperature: 75°F
Thermostat check complete
```
"""

# TODO write the thermostat program
current_temp = 65
desired_temp = 72