# -*- coding: utf-8 -*-
"""For Loops - Exercises.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h4g-R2m3GiwQ6B3RTWdp5NekNXu2GIWj

<img src="https://drive.google.com/uc?id=1uPUwnTqN6FmhirxTGO-nPf-G4lSF3dn5" alt="Banner" width="1500">

# For Loops - Exercises

## Problem 1

A bookstore keeps a list of staff picks for the month:

```python
staff_picks = ["The Alchemist", "Atomic Habits", "Dune", "Sapiens"]
```

Use a for loop to print each title.

**Sample output**
```
The Alchemist
Atomic Habits
Dune
Sapiens
```
"""

staff_picks = ["The Alchemist", "Atomic Habits", "Dune", "Sapiens"]

# TODO: Loop through staff_picks and print each title

"""## Problem 2

The bookstore is assigning temporary ID numbers to 6 new arrivals, starting from 0.

Use a for loop with `range()` to print each ID number.

**Sample output**
```
Book ID: 0
Book ID: 1
Book ID: 2
Book ID: 3
Book ID: 4
Book ID: 5
```
"""

# TODO: Use range() to print Book ID numbers 0 through 5

"""## Problem 3

The bookstore is running a clearance sale and offering a 15% discount on a set of books.

```python
prices = [10.00, 15.00, 20.00, 25.00]
discount = 0.15
```

Use a for loop to print both the original price and the discounted price for each book.

**Sample output**
```
Original: 10.0
Discounted: 8.5
Original: 15.0
Discounted: 12.75
Original: 20.0
Discounted: 17.0
Original: 25.0
Discounted: 21.25
```
"""

prices = [10.00, 15.00, 20.00, 25.00]
discount = 0.15

# TODO: Loop through prices and print both the original and discounted price for each