# -*- coding: utf-8 -*-
"""Lists - Practice Solutions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o6mcSpvcVrgLNU50Mp9rdV11_DoQYcsB

<img src="https://drive.google.com/uc?id=1uPUwnTqN6FmhirxTGO-nPf-G4lSF3dn5" alt="Banner" width="1500">


# Lists - Practice Solutions

# Problem 1

Write a program that stores the names of three of your favorite movies in a list called movies.

Then:
1. Print the entire list
2. Print the first and last movie in the list
3. Change the second movie to a new title of your choice
4. Print the updated list

**Sample output**
```
['Forrest Gump', 'Good Will Hunting', 'The Big Short']
First movie: Forrest Gump
Last movie: The Big Short
Updated list: ['Forrest Gump', 'Princess Bride', 'The Big Short']

```
"""

# TODO: create the list of movies

# Step 1: Print the list
# Step 2: Print the first and last movies
# Step 3: Change the second movie
# Step 4: Print the updated list

"""### Solution"""

movies = ["Forrest Gump", "Good Will Hunting", "The Big Short"]

# Print the entire list
print(movies)

# Access items using indexes
print("First movie:", movies[0])
print("Last movie:", movies[-1])

# Modify the second movie
movies[1] = "Princess Bride"

# Print the updated list
print("Updated list:", movies)

"""# Problem 2
You have a list of friends attending a dinner party: Farah, Alex, Charlie, Dana, Brooke, Eli.

Create the list, then:

1. Use slicing to print only the middle guests (Charlie, Dana, Eli).
2. Add a new friend "Gina" to the end of the list.
3. Remove "Alex" from the list.
4. Print the final sorted list in alphabetical order.

**Sample output**
```
Middle guests: ['Charlie', 'Dana', 'Brooke']
Final guest list: ['Brooke', 'Charlie', 'Dana', 'Eli', 'Farah', 'Gina']
```


"""

# TODO: Create the friends list

# Step 1: Slice to get middle guests
# Step 2: Append a new friend
# Step 3: Remove a friend
# Step 4: Sort and print the final list

"""### Solution"""

friends = ["Farah", "Alex", "Charlie", "Dana", "Brooke", "Eli"]

# Slice middle guests (indexes 2, 3, 4)
middle_guests = friends[2:5]
print("Middle guests:", middle_guests)

# Add new friend
friends.append("Gina")

# Remove Alex
friends.remove("Alex")

# Sort the list
friends.sort()

# Print the final list
print("Final guest list:", friends)

"""# Problem 3
You have two lists of team members:
- Team A: Liam, Olivia, Noah
- Team B: Emma, Ava, Sophia

Create one list for each team, then:
1. Combine both lists into a new list called all_members and print this new list.
2. Add "Mason" to the combined list.
3. Remove "Olivia" from the list.
4. Print the total number of members using the `len()` function.
5. Print the sorted list of all members.

**Sample output**
```
['Liam', 'Olivia', 'Noah', 'Emma', 'Ava', 'Sophia']
Total team members: 6
['Ava', 'Emma', 'Liam', 'Mason', 'Noah', 'Sophia']
```
"""

# TODO: create both lists

# Step 1: Combine lists and print them
# Step 2: Add a new member
# Step 3: Remove a member
# Step 4: Count and print total members
# Step 5: Sort and print final list

"""### Solution"""

team_A = ["Liam", "Olivia", "Noah"]
team_B = ["Emma", "Ava", "Sophia"]

# Combine both lists
all_members = team_A + team_B
print(all_members)

# Add new member
all_members.append("Mason")

# Remove Olivia
all_members.remove("Olivia")

# Count members
print("Total team members:", len(all_members))

# Sort the list
all_members.sort()

# Print final list
print(all_members)